import type { Metadata, Viewport } from "next";
import { Playfair_Display, Montserrat, Bodoni_Moda } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "./registry";
import AnalyticsTracker from "@/src/components/AnalyticsTracker";
import SectionRouteObserver from "@/src/components/SectionRouteObserver";
import SmoothScrolling from "@/src/components/SmoothScrolling";
import ClientChatWidget from "@/src/components/ClientChatWidget";

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["700"],
  style: ["normal", "italic"],
  display: "swap",
});

const bodoni = Bodoni_Moda({
  variable: "--font-bodoni",
  subsets: ["latin"],
  weight: ["700"],
  style: ["normal", "italic"],
  display: "swap",
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "YF Advisors",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfair.variable} ${bodoni.variable} ${montserrat.variable} antialiased`}
      >
        <SmoothScrolling>
          <AnalyticsTracker />
          <SectionRouteObserver />
          {/* WRAP CHILDREN WITH THE REGISTRY COMPONENT */}
          <StyledComponentsRegistry>
            {children}
            <ClientChatWidget />
          </StyledComponentsRegistry>
        </SmoothScrolling>
      </body>
    </html>
  );
}