import type { Metadata } from "next";
import { Playfair_Display, Montserrat, Geist_Mono, Bodoni_Moda, Cormorant_Garamond } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "./registry";
import AnalyticsTracker from "@/src/components/AnalyticsTracker";
import SectionRouteObserver from "@/src/components/SectionRouteObserver";
import SmoothScrolling from "@/src/components/SmoothScrolling";

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
  weight: ["700", "800", "900"],
  style: ["normal", "italic"],
  display: "swap",
});

const bodoni = Bodoni_Moda({
  variable: "--font-bodoni",
  subsets: ["latin"],
  weight: ["600", "700", "800", "900"],
  style: ["normal", "italic"],
  display: "swap",
});

const cormorant = Cormorant_Garamond({
  variable: "--font-cormorant",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  style: ["normal", "italic"],
  display: "swap",
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "YF Advisors",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${playfair.variable} ${bodoni.variable} ${cormorant.variable} ${montserrat.variable} ${geistMono.variable} antialiased`}
      >
        <SmoothScrolling>
          <AnalyticsTracker />
          <SectionRouteObserver />
          {/* WRAP CHILDREN WITH THE REGISTRY COMPONENT */}
          <StyledComponentsRegistry>
            {children}
          </StyledComponentsRegistry>
        </SmoothScrolling>
      </body>
    </html>
  );
}